"""Risk & Customer Value Dashboard (P5).

Answers the sales manager's third question: *Where are the biggest risks and
who are the most valuable customers?*

Themes covered (per team plan):
    * Returns        -> return value, return rate and most-returned products
    * Customer value -> top customers by revenue
    * Concentration  -> how dependent revenue is on a few customers / large orders
    * Insights       -> automatic business-risk highlights

The page is self-contained (it inlines its data prep) so it keeps working even
if the shared ``src`` backend changes, matching the rest of the app.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Use the shared cached loaders when available, otherwise fall back to cached
# local readers. ``load_cancellations`` is the backend name for the returns file.
try:
    from src.data_loader import load_sales, load_cancellations as load_returns
except Exception:  # pragma: no cover - defensive fallback
    @st.cache_data
    def load_sales():
        return pd.read_parquet("data/retail_clean.parquet")

    @st.cache_data
    def load_returns():
        return pd.read_parquet("data/retail_cancellations.parquet")


def normalize_columns_local(df):
    """Rename the many possible raw column spellings to canonical names."""
    rename_map = {
        "Customer ID": "CustomerID",
        "Customer_ID": "CustomerID",
        "customer_id": "CustomerID",
        "CustomerNo": "CustomerID",
        "Customer No": "CustomerID",
        "Invoice No": "InvoiceNo",
        "Invoice_No": "InvoiceNo",
        "invoice_no": "InvoiceNo",
        "InvoiceNumber": "InvoiceNo",
        "Invoice Number": "InvoiceNo",
        "Invoice": "InvoiceNo",
        "invoice": "InvoiceNo",
        "Unit Price": "UnitPrice",
        "Unit_Price": "UnitPrice",
        "unit_price": "UnitPrice",
        "Price": "UnitPrice",
        "price": "UnitPrice",
        "Rate": "UnitPrice",
        "Invoice Date": "InvoiceDate",
        "Invoice_Date": "InvoiceDate",
        "invoice_date": "InvoiceDate",
        "Date": "InvoiceDate",
        "date": "InvoiceDate",
    }
    return df.rename(columns=rename_map)


def _add_revenue(df):
    """Ensure a ``Revenue`` column exists (Quantity * UnitPrice)."""
    if "Revenue" not in df.columns and {"Quantity", "UnitPrice"} <= set(df.columns):
        df = df.copy()
        df["Revenue"] = df["Quantity"] * df["UnitPrice"]
    return df


@st.cache_data
def get_sales():
    """Load + normalise the sales dataset once (cached across reruns)."""
    return _add_revenue(normalize_columns_local(load_sales()))


@st.cache_data
def get_returns():
    """Load + normalise the returns/cancellations dataset once (cached)."""
    df = load_returns()
    if df is None or df.empty:
        return pd.DataFrame()
    return _add_revenue(normalize_columns_local(df))


def filter_country_local(df, country):
    """Restrict a frame to a single country (or pass through for 'All')."""
    if df.empty:
        return df
    if "Country" in df.columns and country != "All Countries":
        return df[df["Country"] == country]
    return df


def top_customers(df, n):
    """Top ``n`` customers by revenue, with their order counts."""
    if not {"CustomerID", "Revenue"} <= set(df.columns):
        return pd.DataFrame(columns=["CustomerID", "Revenue", "Orders"])
    clean = df.dropna(subset=["CustomerID"])
    if clean.empty:
        return pd.DataFrame(columns=["CustomerID", "Revenue", "Orders"])
    agg = {"Revenue": ("Revenue", "sum")}
    if "InvoiceNo" in clean.columns:
        agg["Orders"] = ("InvoiceNo", "nunique")
    out = clean.groupby("CustomerID").agg(**agg).reset_index()
    out["CustomerID"] = out["CustomerID"].astype("int64").astype(str)
    return out.sort_values("Revenue", ascending=False).head(n)


def customer_concentration(df):
    """Share of revenue generated by the top 10% of customers (0-100)."""
    if not {"CustomerID", "Revenue"} <= set(df.columns):
        return 0.0
    cust = df.dropna(subset=["CustomerID"]).groupby("CustomerID")["Revenue"].sum()
    cust = cust.sort_values(ascending=False)
    total = cust.sum()
    if len(cust) == 0 or total <= 0:
        return 0.0
    top_n = max(1, int(len(cust) * 0.10))
    return cust.head(top_n).sum() / total * 100.0


def order_pareto(df):
    """Build the revenue-concentration (Pareto) curve over orders.

    Orders are ranked largest-first; the returned frame traces cumulative % of
    orders against cumulative % of revenue. ``top20`` is the headline metric:
    the share of revenue coming from the largest 20% of transactions.
    Returns ``(curve_df, top20_pct)``.
    """
    empty = pd.DataFrame(columns=["Cumulative % of Orders", "Cumulative % of Revenue"])
    if not {"InvoiceNo", "Revenue"} <= set(df.columns):
        return empty, 0.0

    order_rev = df.groupby("InvoiceNo")["Revenue"].sum()
    order_rev = order_rev[order_rev > 0].sort_values(ascending=False)
    n = len(order_rev)
    if n == 0:
        return empty, 0.0

    cum_rev = order_rev.cumsum().to_numpy()
    total = cum_rev[-1]
    cum_share = cum_rev / total * 100.0
    order_share = np.arange(1, n + 1) / n * 100.0

    top20 = order_rev.head(max(1, int(n * 0.20))).sum() / total * 100.0

    # Down-sample so the plotted line stays light regardless of order count.
    idx = np.unique(np.linspace(0, n - 1, 250).astype(int)) if n > 250 else np.arange(n)
    curve = pd.DataFrame(
        {
            "Cumulative % of Orders": np.concatenate([[0.0], order_share[idx]]),
            "Cumulative % of Revenue": np.concatenate([[0.0], cum_share[idx]]),
        }
    )
    return curve, top20


def render():
    st.title("⚠️ Risk & Customer Value")
    st.markdown(
        "Surface the biggest risks in the business — returns, revenue reliance on a "
        "handful of buyers, and dependency on large transactions — while spotlighting "
        "the most valuable customers."
    )

    # ---- Data ---------------------------------------------------------------
    try:
        df_sales = get_sales()
        df_returns = get_returns()
    except Exception as e:
        st.error(f"Error loading data files: {e}")
        st.stop()

    # ---- Filters ------------------------------------------------------------
    st.sidebar.header("Global Filters")
    countries = (
        sorted(df_sales["Country"].dropna().unique().tolist())
        if "Country" in df_sales.columns
        else []
    )
    selected_country = st.sidebar.selectbox(
        "Select Country", ["All Countries"] + countries, key="p5_country"
    )
    top_n = st.sidebar.slider("Show Top N", min_value=5, max_value=20, value=10, key="p5_topn")

    df_sales_f = filter_country_local(df_sales, selected_country)
    df_returns_f = filter_country_local(df_returns, selected_country)

    if df_sales_f.empty:
        st.warning("No sales records found for the selected market.")
        st.stop()

    # ---- Metrics ------------------------------------------------------------
    sales_val = float(df_sales_f["Revenue"].sum()) if "Revenue" in df_sales_f.columns else 0.0
    returns_val = (
        abs(float(df_returns_f["Revenue"].sum()))
        if not df_returns_f.empty and "Revenue" in df_returns_f.columns
        else 0.0
    )
    r_rate = (returns_val / sales_val * 100.0) if sales_val > 0 else 0.0

    concentration_pct = customer_concentration(df_sales_f)
    pareto_curve, top20_pct = order_pareto(df_sales_f)

    k1, k2, k3, k4 = st.columns(4)
    with k1:
        st.metric(
            "Total Return Value",
            f"${returns_val:,.0f}",
            help="Money lost to returns/cancellations in the current selection.",
        )
    with k2:
        st.metric(
            "Return Rate",
            f"{r_rate:.2f}%",
            help="Return value as a percentage of total sales revenue.",
        )
    with k3:
        st.metric(
            "Top 10% Customer Share",
            f"{concentration_pct:.1f}%",
            help="Revenue share generated by the top 10% of customers.",
        )
    with k4:
        st.metric(
            "Top 20% Order Share",
            f"{top20_pct:.1f}%",
            help="Revenue share coming from the largest 20% of transactions.",
        )

    st.markdown("---")

    # ---- Returns & Customers ------------------------------------------------
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Most Returned Products")
        if (
            not df_returns_f.empty
            and {"Description", "Quantity"} <= set(df_returns_f.columns)
        ):
            returned = (
                df_returns_f.groupby("Description")
                .agg(Units=("Quantity", "sum"), Value=("Revenue", "sum"))
                .reset_index()
            )
            returned["Units"] = returned["Units"].abs()
            returned["Value"] = returned["Value"].abs()
            returned = returned.sort_values("Units", ascending=False).head(top_n)

            fig_returns = px.bar(
                returned,
                x="Description",
                y="Units",
                title=f"Top {top_n} Returned Products by Volume",
                labels={"Units": "Units Returned", "Description": "Product"},
                hover_data={"Value": ":,.0f"},
            )
            fig_returns.update_traces(marker_color="#E05A47")
            fig_returns.update_layout(
                template="plotly_white", margin=dict(l=10, r=10, t=40, b=10)
            )
            st.plotly_chart(fig_returns, width="stretch")
        else:
            st.info("No returns recorded for the selected market.")

    with col_right:
        st.subheader("Most Valuable Customers")
        df_cust = top_customers(df_sales_f, top_n)
        if not df_cust.empty:
            hover = {"Orders": True} if "Orders" in df_cust.columns else None
            fig_cust = px.bar(
                df_cust.sort_values("Revenue", ascending=True),
                x="Revenue",
                y="CustomerID",
                orientation="h",
                title=f"Top {top_n} Customers by Revenue",
                labels={"Revenue": "Revenue ($)", "CustomerID": "Customer"},
                hover_data=hover,
            )
            fig_cust.update_traces(marker_color="#2B4C7E")
            fig_cust.update_layout(
                template="plotly_white", margin=dict(l=10, r=10, t=40, b=10)
            )
            st.plotly_chart(fig_cust, width="stretch")
        else:
            st.info("No identifiable customers in the selected market.")

    st.markdown("---")

    # ---- Revenue Concentration (Pareto) -------------------------------------
    st.subheader("Revenue Concentration — Dependency on Large Transactions")
    st.caption(
        "Orders are ranked largest-first. The further the curve bows above the "
        "dashed line, the more the business leans on a small number of big orders."
    )
    if not pareto_curve.empty:
        fig_par = px.area(
            pareto_curve,
            x="Cumulative % of Orders",
            y="Cumulative % of Revenue",
            title="Cumulative Revenue vs. Cumulative Orders",
        )
        fig_par.update_traces(
            line_color="#29B5E8", fillcolor="rgba(41,181,232,0.15)", line_width=3
        )
        # Reference: perfect equality (every order contributes the same revenue).
        fig_par.add_shape(
            type="line", x0=0, y0=0, x1=100, y1=100,
            line=dict(color="#B0B0B0", dash="dash"),
        )
        fig_par.add_annotation(
            x=78, y=72, text="Perfect equality", showarrow=False,
            font=dict(color="#9A9A9A", size=12),
        )
        fig_par.update_layout(
            template="plotly_white",
            margin=dict(l=10, r=10, t=40, b=10),
            xaxis=dict(range=[0, 100]),
            yaxis=dict(range=[0, 100]),
        )
        st.plotly_chart(fig_par, width="stretch")
    else:
        st.info("Not enough order data to compute revenue concentration.")

    st.markdown("---")

    # ---- Automatic Risk Insights -------------------------------------------
    st.subheader("💡 Business Risk Insights")

    # 1) Returns pressure
    if r_rate >= 5:
        st.warning(
            f"🔴 **Elevated Returns:** Returns equal **{r_rate:.1f}%** of sales value "
            f"(**${returns_val:,.0f}** lost). Review the most-returned lines and the "
            "refund/adjustment workflow to recover margin."
        )
    elif r_rate >= 2:
        st.info(
            f"🟡 **Moderate Returns:** Returns run at **{r_rate:.1f}%** of sales "
            f"(**${returns_val:,.0f}**). Worth monitoring, but within a manageable range."
        )
    else:
        st.success(
            f"🟢 **Low Returns:** Returns are just **{r_rate:.1f}%** of sales value — "
            "product satisfaction and fulfilment quality look healthy."
        )

    # 2) Customer concentration
    if concentration_pct > 50:
        st.warning(
            f"⚠️ **Customer Concentration Risk:** The top 10% of customers drive "
            f"**{concentration_pct:.1f}%** of revenue. The business is heavily reliant on "
            "a few accounts — invest in key-account management and loyalty safeguards to "
            "reduce churn exposure."
        )
    else:
        st.success(
            f"🟢 **Healthy Customer Diversification:** The top 10% of customers account "
            f"for **{concentration_pct:.1f}%** of revenue, so income is spread across the base."
        )

    # 3) Large-transaction dependency
    if top20_pct >= 60:
        st.warning(
            f"📊 **Large-Transaction Dependency:** The largest 20% of orders generate "
            f"**{top20_pct:.1f}%** of revenue. A slowdown in high-value orders would hit the "
            "top line hard — diversify toward more mid-sized transactions."
        )
    else:
        st.info(
            f"📊 **Balanced Order Mix:** The largest 20% of orders contribute "
            f"**{top20_pct:.1f}%** of revenue, indicating reasonably distributed transaction sizes."
        )

    # 4) Spotlight the single biggest return driver, when available
    if not df_returns_f.empty and {"Description", "Revenue"} <= set(df_returns_f.columns):
        by_value = df_returns_f.groupby("Description")["Revenue"].sum().abs().sort_values(ascending=False)
        if not by_value.empty:
            st.info(
                f"🔎 **Top Return Driver:** **{by_value.index[0]}** accounts for the largest "
                f"return value at **${by_value.iloc[0]:,.0f}** — a prime candidate for a "
                "root-cause review."
            )
