import streamlit as st
from src.data_loader import load_sales, load_returns, filter_country
from src.charts import returns_chart, customer_chart
from src.analysis import return_rate, revenue_concentration

st.title("⚠️ Risk & Customer Value")
st.markdown("Understand high-risk elements of the business, return statistics, and customer reliance/loyalty indexes.")

# Load sales & cancellation datasets
try:
    df_sales = load_sales()
    df_returns = load_returns()
except Exception as e:
    st.error(f"Error loading files: {e}")
    st.stop()

# Sidebar filter
st.sidebar.header("Global Filters")
unique_countries = sorted(df_sales["Country"].dropna().unique().tolist())
selected_country = st.sidebar.selectbox("Select Country", ["All Countries"] + unique_countries, key="p5_country")

df_sales_filt = filter_country(df_sales, selected_country)
df_returns_filt = filter_country(df_returns, selected_country) if not df_returns.empty else df_returns

# Row 1: KPI Statistics
r_rate = return_rate(df_sales_filt, df_returns_filt)
concentration_pct = revenue_concentration(df_sales_filt)

col1, col2 = st.columns(2)
with col1:
    st.metric(
        label="Return Rate (%)",
        value=f"{r_rate:.2f}%",
        help="Value of returns as a percentage of total positive sales revenue."
    )
with col2:
    st.metric(
        label="Top 10% Customer Concentration",
        value=f"{concentration_pct:.1f}%",
        help="Percentage of total revenue generated by the top 10% of customers."
    )

st.markdown("---")

# Row 2: Visualizations
col_left, col_right = st.columns(2)

with col_left:
    fig_returns = returns_chart(df_returns_filt)
    st.plotly_chart(fig_returns, use_container_width=True)

with col_right:
    fig_cust = customer_chart(df_sales_filt)
    st.plotly_chart(fig_cust, use_container_width=True)

st.markdown("---")

# Insights Box
st.subheader("💡 Risk Mitigation Strategy")
if concentration_pct > 50:
    st.warning(
        f"⚠️ **High Concentration Risk:** The top 10% of your buyers generate **{concentration_pct:.1f}%** of total revenue. "
        "The business is highly dependent on a small group of repeat purchasers. Introduce key-account management loyalty rewards to reduce churn risk."
    )
else:
    st.success(
        "🟢 **Healthy Diversification:** Customer reliance is healthy. Revenue is spread evenly among your customer base, limiting downside impact if a major account is lost."
    )